/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui {
    export class agameUI extends Laya.View {
		public back_login:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("agame");
        }
    }
    REG("ui.agameUI",agameUI);
    export class loginUI extends Laya.View {
		public btn_login:Laya.Button;
		public btn_regist:Laya.Button;
		public btn_try:Laya.Button;
		public label_account:Laya.TextInput;
		public label_password:Laya.TextInput;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("login");
        }
    }
    REG("ui.loginUI",loginUI);
    export class registUI extends Laya.View {
		public btn_back_login:Laya.Button;
		public btn_reg_confirm:Laya.Button;
		public label_account:Laya.TextInput;
		public label_psw:Laya.TextInput;
		public label_psw_confirm:Laya.TextInput;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("regist");
        }
    }
    REG("ui.registUI",registUI);
}